version: "3.8"
services:
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "8080:80"
    nodeserver:
        build:
            context: ./nodejs
        ports:
            - "1234:3000"
    redis-server:
        image: 'redis'
        ports:
            - "6379:6379"
